FROM python

WORKDIR /app

COPY . /app

CMD ["python", "rng.py"]

#now we build it:
#       docker build .
#And to run it, we need to do it in -i (interactive mode) and -t it creates a terminal
#This way the container will listed to our input and will get a terminal exposed by the container where we enter the input
